name: "Docker Build Composite Action"
description: "Docker build with cache and optional build arguments."

# TODO(Jack): Allow the user to to use multiple external cache scopes (if it becomes needed).

inputs:
  build-args:
    required: false
  cache_scope:
    required: true
  context:
    required: false
  external_cache_scope:
    required: false
  file:
    default: building/Dockerfile
    required: false
  target:
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        build-args: ${{ inputs.build-args }}
        # NOTE(Jack: The external cache line here is very complicated! But its simple - if the external_cache_scope is
        # provided then it gets included in addition to cache_scope, if it's not then only the cache_scope is included.
        # If we did not do the conditional logic then external_cache_scope would be an empty string and the cache-from
        # in the docker build command would be set like '--cache-from type=gha,scope=' which smells to me! With the
        # conditional logic the second cache-from flag will simply not be present.
        cache-from: |
          type=gha,scope=${{ inputs.cache_scope }}
          ${{ inputs.external_cache_scope && format('type=gha,scope={0}', inputs.external_cache_scope) || '' }}
        cache-to: type=gha,mode=max,scope=${{ inputs.cache_scope }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        target: ${{ inputs.target }}