name: CI

# TODO(Jack): Currently the base stages are not available for reuse in one generic cached stage. We should be able to do
# this for the ubuntu 24 build path using the external_cache_scope.

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          cache_scope: code-checks
          target: code-checks-stage
  code-checks-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          cache_scope: code-checks-python
          target: code-checks-python-stage
  debug-build:
    needs: code-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          cache_scope: debug-build
          target: debug-build-stage
  code-coverage-assertion:
    needs: debug-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          cache_scope: code-coverage-assertion
          external_cache_scope: debug-build
          target: code-coverage-assertion-stage
  python-tooling:
    needs: code-checks-python
    runs-on: ubuntu-latest
    steps:
      # Objects stored with git-lfs need to be pulled, we follow the example at this link:
      # https://github.com/roim/docker-action-lfs/blob/main/.github/workflows/custom-context--working.yml
      - uses: actions/checkout@v5
        with:
          lfs: true
      - run: git lfs pull
      - uses: ./.github/actions/docker-build
        with:
          context: .
          cache_scope: python-tooling
          target: python-tooling-stage
  test-data-download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          cache_scope: test-data-download
          target: test-data-download-stage
  applications:
    # NOTE(Jack): The applications actually do release builds of the library themselves, but to prevent the risk of us having
    # multiple library builds failing for the same reason, we make the applications depend on a successful debug-build.
    # NOTE(Jack): Network resource use is expensive so we make the applications depend on and cache from a common
    # test-data-download stage. If we did not explicitly have the download step and cache from it each application would
    # itself download and cache the data. Wasteful.
    needs: [ debug-build, test-data-download ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - run: git lfs pull
      - uses: actions/checkout@v5
      - uses: ./.github/actions/docker-build
        with:
          build-args: BASE_IMAGE=${{ matrix.applications.base }}
          cache_scope: ${{ matrix.applications.cache_scope }}
          context: .
          external_cache_scope: test-data-download
          target: ${{ matrix.applications.target }}
    strategy:
      matrix:
        applications:
          - base: ubuntu:20.04@sha256:8feb4d8ca5354def3d8fce243717141ce31e2c428701f6682bd2fafe15388214
            name: ros1
            cache_scope: ros1-application
            target: ros1-integration-test-stage
          - base: ubuntu:24.04@sha256:186072bba1b2f436cbb91ef2567abca677337cfc786c86e107d25b7072feef0c
            name: ros2
            cache_scope: ros2-application
            target: ros2-integration-test-stage
