name: "Docker Build"
description: "Reusable docker build gha job with GHA cache and optional build arguments"

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      scope:
        required: true
        type: string
      file:
        default: building/Dockerfile
        required: false
        type: string
      build-args:
        required: false
        type: string

jobs:
  reusable_docker_build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha,scope=${{ inputs.scope }}
          cache-to: type=gha,mode=max,scope=${{ inputs.scope }}
          file: ${{ inputs.file }}
          target: ${{ inputs.target }}