name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: code-checks-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: building/Dockerfile
          push: true
          tags: reprojection-code-checks:latest
          target: code-checks-stage
      - name: build-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: building/Dockerfile
          push: true
          tags: reprojection-build:latest
          target: build-stage
      - name: code-coverage-assertion-stage
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: building/Dockerfile
          push: true
          tags: reprojection-code-coverage-assertion:latest
          target: code-coverage-assertion-stage